/**
 * NextVisitScheduleConstants
 *
 * @package                Safe Health
 * @subpackage             NextVisitScheduleConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Next Visit Schedule Constants
 */
export const NextVisitScheduleConstants = {
	NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_REQUEST 		: 'NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_REQUEST',
	NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_SUCCESS 		: 'NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_SUCCESS',
	NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_FAILURE 		: 'NEW_VISIT_SCHEDULE_APPOINTMENT_TIME_FAILURE',
	NEW_VISIT_SCHEDULE_RESET_STATE 						: 'NEW_VISIT_SCHEDULE_RESET_STATE',
	NEW_VISIT_SCHEDULE_ADD_REQUEST						: 'NEW_VISIT_SCHEDULE_ADD_REQUEST',
	NEW_VISIT_SCHEDULE_ADD_FAILURE						: 'NEW_VISIT_SCHEDULE_ADD_FAILURE',
	NEW_VISIT_SCHEDULE_ADD_SUCCESS						: 'NEW_VISIT_SCHEDULE_ADD_SUCCESS',
	NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_REQUEST 	: 'NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_REQUEST',
	NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_SUCCESS 	: 'NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_SUCCESS',
	NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_FAILURE 	: 'NEW_VISIT_SCHEDULE_APPOINTMENT_CLINIC_LIST_FAILURE',
	PAT_NEXT_VISIT_SCHEDULE_REQUEST 					: 'PAT_NEXT_VISIT_SCHEDULE_REQUEST',
	PAT_NEXT_VISIT_SCHEDULE_SUCCESS 					: 'PAT_NEXT_VISIT_SCHEDULE_SUCCESS',
	PAT_NEXT_VISIT_SCHEDULE_FAILURE 					: 'PAT_NEXT_VISIT_SCHEDULE_FAILURE',
};
