/**
 * patientDiagnosisConstants
 *
 * @package                Safe Health
 * @subpackage             patientDiagnosisConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientDiagnosisConstants = {
	DIAGNOSIS_OPTION_REQUEST			: 'DIAGNOSIS_OPTION_REQUEST',
	DIAGNOSIS_OPTION_FAILURE			: 'DIAGNOSIS_OPTION_FAILURE',
	DIAGNOSIS_OPTION_SUCCESS			: 'DIAGNOSIS_OPTION_SUCCESS',
	DIAGNOSIS_ADD_REQUEST				: 'DIAGNOSIS_ADD_REQUEST',
	DIAGNOSIS_ADD_FAILURE				: 'DIAGNOSIS_ADD_FAILURE',
	DIAGNOSIS_ADD_SUCCESS				: 'DIAGNOSIS_ADD_SUCCESS',
	DIAGNOSIS_GRID_REQUEST				: 'DIAGNOSIS_GRID_REQUEST',
	DIAGNOSIS_GRID_FAILURE				: 'DIAGNOSIS_GRID_FAILURE',
	DIAGNOSIS_GRID_SUCCESS				: 'DIAGNOSIS_GRID_SUCCESS',
	DIAGNOSIS_REST_ADD				    : 'DIAGNOSIS_REST_ADD',
	DIAGNOSIS_UPDATE_REQUEST			: 'DIAGNOSIS_UPDATE_REQUEST',
	DIAGNOSIS_UPDATE_FAILURE			: 'DIAGNOSIS_UPDATE_FAILURE',
	DIAGNOSIS_UPDATE_SUCCESS			: 'DIAGNOSIS_UPDATE_SUCCESS',
	DIAGNOSIS_DELETE_REQUEST			: 'DIAGNOSIS_DELETE_REQUEST',
	DIAGNOSIS_DELETE_FAILURE			: 'DIAGNOSIS_DELETE_FAILURE',
	DIAGNOSIS_DELETE_SUCCESS			: 'DIAGNOSIS_DELETE_SUCCESS',
	DIAGNOSIS_FORM_DATA_REQUEST			: 'DIAGNOSIS_FORM_DATA_REQUEST',
	DIAGNOSIS_FORM_DATA_FAILURE			: 'DIAGNOSIS_FORM_DATA_FAILURE',
	DIAGNOSIS_FORM_DATA_SUCCESS			: 'DIAGNOSIS_FORM_DATA_SUCCESS',
	DIAGNOSIS_FACTOR_ADD_REQUEST		: 'DIAGNOSIS_FACTOR_ADD_REQUEST',
	DIAGNOSIS_FACTOR_ADD_SUCCESS		: 'DIAGNOSIS_FACTOR_ADD_SUCCESS',
	DIAGNOSIS_FACTOR_ADD_FAILURE		: 'DIAGNOSIS_FACTOR_ADD_FAILURE',
};
