/**
 * patientLaboratoryReportConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             patientLaboratoryReportConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientLaboratoryReportConstants = {
	LABORATORY_TEMP_REQUEST									: 'LABORATORY_TEMP_REQUEST',
	LABORATORY_TEMP_FAILURE									: 'LABORATORY_TEMP_FAILURE',
	LABORATORY_TEMP_SUCCESS									: 'LABORATORY_TEMP_SUCCESS',
	PATIENT_LABORATORY_REPORT_ADD_REQUEST					: 'PATIENT_LABORATORY_REPORT_ADD_REQUEST',
	PATIENT_LABORATORY_REPORT_ADD_FAILURE					: 'PATIENT_LABORATORY_REPORT_ADD_FAILURE',
	PATIENT_LABORATORY_REPORT_ADD_SUCCESS					: 'PATIENT_LABORATORY_REPORT_ADD_SUCCESS',
	PATIENT_LABORATORY_REPORT_GRID_REQUEST					: 'PATIENT_LABORATORY_REPORT_GRID_REQUEST',
	PATIENT_LABORATORY_REPORT_GRID_FAILURE					: 'PATIENT_LABORATORY_REPORT_GRID_FAILURE',
	PATIENT_LABORATORY_REPORT_GRID_SUCCESS					: 'PATIENT_LABORATORY_REPORT_GRID_SUCCESS',
	PATIENT_LABORATORY_REPORT_DELETE_REQUEST				: 'PATIENT_LABORATORY_REPORT_DELETE_REQUEST',
	PATIENT_LABORATORY_REPORT_DELETE_FAILURE				: 'PATIENT_LABORATORY_REPORT_DELETE_FAILURE',
	PATIENT_LABORATORY_REPORT_DELETE_SUCCESS				: 'PATIENT_LABORATORY_REPORT_DELETE_SUCCESS',
	PATIENT_LABORATORY_REPORT_RESET				    		: 'PATIENT_LABORATORY_REPORT_RESET',
	PATIENT_LABORATORY_REPORT_DOWNLOAD_REQUEST				: 'PATIENT_LABORATORY_REPORT_DOWNLOAD_REQUEST',
	PATIENT_LABORATORY_REPORT_DOWNLOAD_SUCCESS				: 'PATIENT_LABORATORY_REPORT_DOWNLOAD_SUCCESS',
	PATIENT_LABORATORY_REPORT_DOWNLOAD_FAILURE				: 'PATIENT_LABORATORY_REPORT_DOWNLOAD_FAILURE',
	SHOW_LAB_REPORT_REQUEST 								: 'SHOW_LAB_REPORT_REQUEST', 
	SHOW_LAB_REPORT_SUCCESS 								: 'SHOW_LAB_REPORT_SUCCESS', 
	SHOW_LAB_REPORT_FAILURE 								: 'SHOW_LAB_REPORT_FAILURE', 
};
