/**
 * medicationConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             medicationConstants
 * @category               Constants
 * @DateOfCreation         3 July 2018
 * @ShortDescription       This is responsible for get static data action names
 */
export const medicationConstants = {
	MEDICINE_LIST_DATA_REQUEST	: 'MEDICINE_LIST_DATA_REQUEST',
	MEDICINE_LIST_DATA_SUCCESS	: 'MEDICINE_LIST_DATA_SUCCESS',
	MEDICINE_LIST_DATA_FAILURE	: 'MEDICINE_LIST_DATA_FAILURE',

	MEDICATION_EDIT_REQUEST		: 'MEDICATION_EDIT_REQUEST',
	MEDICATION_EDIT_SUCCESS		: 'MEDICATION_EDIT_SUCCESS',
	MEDICATION_EDIT_FAILURE		: 'MEDICATION_EDIT_FAILURE',

	MEDICATION_DELETE_REQUEST	: 'MEDICATION_DELETE_REQUEST',
	MEDICATION_DELETE_SUCCESS	: 'MEDICATION_DELETE_SUCCESS',
	MEDICATION_DELETE_FAILURE	: 'MEDICATION_DELETE_FAILURE',

	DISCONTINUE_MEDICATION_REQUEST	: 'DISCONTINUE_MEDICATION_REQUEST',
	DISCONTINUE_MEDICATION_SUCCESS	: 'DISCONTINUE_MEDICATION_SUCCESS',
	DISCONTINUE_MEDICATION_FAILURE	: 'DISCONTINUE_MEDICATION_FAILURE',

	PATIENT_MEDICINE_DATA_REQUEST: 'PATIENT_MEDICINE_DATA_REQUEST',
	PATIENT_MEDICINE_DATA_SUCCESS: 'PATIENT_MEDICINE_DATA_SUCCESS',
	PATIENT_MEDICINE_DATA_FAILURE: 'PATIENT_MEDICINE_DATA_FAILURE',

	GET_MEDICINE_DATA_REQUEST	: 'GET_MEDICINE_DATA_REQUEST',
	GET_MEDICINE_DATA_SUCCESS	: 'GET_MEDICINE_DATA_SUCCESS',
	GET_MEDICINE_DATA_FAILURE	: 'GET_MEDICINE_DATA_FAILURE',
	
	MEDICATIONS_RESET_STATE		: 'MEDICATIONS_RESET_STATE',
	MEDICATION_TEMP_REQUEST		: 'MEDICATION_TEMP_REQUEST',
	MEDICATION_TEMP_SUCCESS		: 'MEDICATION_TEMP_SUCCESS',
	MEDICATION_TEMP_FAILURE		: 'MEDICATION_TEMP_FAILURE',

	MEDICINE_TEMP_DATA_REQUEST	: 'MEDICINE_TEMP_DATA_REQUEST',
	MEDICINE_TEMP_DATA_SUCCESS	: 'MEDICINE_TEMP_DATA_SUCCESS',
	MEDICINE_TEMP_DATA_FAILURE	: 'MEDICINE_TEMP_DATA_FAILURE',
	MEDICATIONS_RESET_STATE_TEMPLATE_DATA_FETCHED : 'MEDICATIONS_RESET_STATE_TEMPLATE_DATA_FETCHED',

	MEDICINE_TEMP_FETCH_REQUEST	: 'MEDICINE_TEMP_FETCH_REQUEST',
	MEDICINE_TEMP_FETCH_SUCCESS	: 'MEDICINE_TEMP_FETCH_SUCCESS',
	MEDICINE_TEMP_FETCH_FAILURE	: 'MEDICINE_TEMP_FETCH_FAILURE',

	SEARCH_MEDICINE_REQUEST 	: 'SEARCH_MEDICINE_REQUEST',
	SEARCH_MEDICINE_SUCCESS 	: 'SEARCH_MEDICINE_SUCCESS',
	SEARCH_MEDICINE_FAILURE 	: 'SEARCH_MEDICINE_FAILURE',
};
