/**
 * patientDashboardProfileConstants
 *
 * @package                ILD India Registry
 * @subpackage             patientDashboardProfileConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientDashboardProfileConstants = {    
    LOGGED_IN									: 'LOGGED_IN',
    LOGGED_OUT									: 'LOGGED_OUT',
    PATIENT_DASHBOARD_MEDICATION_REQUEST		: 'PATIENT_DASHBOARD_MEDICATION_REQUEST',
	PATIENT_DASHBOARD_MEDICATION_SUCCESS		: 'PATIENT_DASHBOARD_MEDICATION_SUCCESS',
	PATIENT_DASHBOARD_MEDICATION_FAILURE		: 'PATIENT_DASHBOARD_MEDICATION_FAILURE',
	PATIENT_DASHBOARD_PROFILE_REQUEST			: 'PATIENT_DASHBOARD_PROFILE_REQUEST',
	PATIENT_DASHBOARD_PROFILE_FAILURE			: 'PATIENT_DASHBOARD_PROFILE_FAILURE',
	PATIENT_DASHBOARD_PROFILE_SUCCESS			: 'PATIENT_DASHBOARD_PROFILE_SUCCESS',

	PATIENT_DASHBOARD_PROFILE_UNAUTHENTICATE	: 'PATIENT_DASHBOARD_PROFILE_UNAUTHENTICATE',
	PATIENT_DASHBOARD_PROFILE_RESET_STATE		: 'PATIENT_DASHBOARD_PROFILE_RESET_STATE',
	PATIENT_DASHBOARD_UNAUTHENTICATE			: 'PATIENT_DASHBOARD_UNAUTHENTICATE',
};