/**
 * patientMedicalHistoryConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             patientMedicalHistoryConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientMedicalHistoryConstants = {
	PATIENT_MEDICAL_HISTORY_ADD_REQUEST					: 'PATIENT_MEDICAL_HISTORY_ADD_REQUEST',
	PATIENT_MEDICAL_HISTORY_ADD_FAILURE					: 'PATIENT_MEDICAL_HISTORY_ADD_FAILURE',
	PATIENT_MEDICAL_HISTORY_ADD_SUCCESS					: 'PATIENT_MEDICAL_HISTORY_ADD_SUCCESS',
	PATIENT_MEDICAL_HISTORY_GRID_REQUEST				: 'PATIENT_MEDICAL_HISTORY_GRID_REQUEST',
	PATIENT_MEDICAL_HISTORY_GRID_FAILURE				: 'PATIENT_MEDICAL_HISTORY_GRID_FAILURE',
	PATIENT_MEDICAL_HISTORY_GRID_SUCCESS				: 'PATIENT_MEDICAL_HISTORY_GRID_SUCCESS',
	PATIENT_MEDICAL_HISTORY_DELETE_REQUEST				: 'PATIENT_MEDICAL_HISTORY_DELETE_REQUEST',
	PATIENT_MEDICAL_HISTORY_DELETE_FAILURE				: 'PATIENT_MEDICAL_HISTORY_DELETE_FAILURE',
	PATIENT_MEDICAL_HISTORY_DELETE_SUCCESS				: 'PATIENT_MEDICAL_HISTORY_DELETE_SUCCESS',
	PATIENT_MEDICAL_HISTORY_RESET				    	: 'PATIENT_MEDICAL_HISTORY_RESET',
};
