/**
 * patientWorkEnvironmentConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             patientWorkEnvironmentConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientWorkEnvironmentConstants = {
	WORK_ENVIRONMENT_FACTOR_ADD_REQUEST					: 'WORK_ENVIRONMENT_FACTOR_ADD_REQUEST',
	WORK_ENVIRONMENT_FACTOR_ADD_FAILURE					: 'WORK_ENVIRONMENT_FACTOR_ADD_FAILURE',
	WORK_ENVIRONMENT_FACTOR_ADD_SUCCESS					: 'WORK_ENVIRONMENT_FACTOR_ADD_SUCCESS',
	WORK_ENVIRONMENT_FACTOR_GRID_REQUEST				: 'WORK_ENVIRONMENT_FACTOR_GRID_REQUEST',
	WORK_ENVIRONMENT_FACTOR_GRID_FAILURE				: 'WORK_ENVIRONMENT_FACTOR_GRID_FAILURE',
	WORK_ENVIRONMENT_FACTOR_GRID_SUCCESS				: 'WORK_ENVIRONMENT_FACTOR_GRID_SUCCESS',
	WORK_ENVIRONMENT_FACTOR_DELETE_REQUEST				: 'WORK_ENVIRONMENT_FACTOR_DELETE_REQUEST',
	WORK_ENVIRONMENT_FACTOR_DELETE_FAILURE				: 'WORK_ENVIRONMENT_FACTOR_DELETE_FAILURE',
	WORK_ENVIRONMENT_FACTOR_DELETE_SUCCESS				: 'WORK_ENVIRONMENT_FACTOR_DELETE_SUCCESS',
	WORK_ENVIRONMENT_FACTOR_RESET				    	: 'WORK_ENVIRONMENT_FACTOR_RESET',
};
