/**
 * labTemplatesConstants
 *
 * @package                Safe Helth
 * @subpackage             labTemplatesConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for add lab templates
 */
export const labTemplatesConstants = {
	LAB_TEMPLATES_ADD_REQUEST				: 'LAB_TEMPLATES_ADD_REQUEST',
	LAB_TEMPLATES_ADD_FAILURE				: 'LAB_TEMPLATES_ADD_FAILURE',
	LAB_TEMPLATES_ADD_SUCCESS				: 'LAB_TEMPLATES_ADD_SUCCESS',
	LAB_TEMPLATES_GRID_REQUEST				: 'LAB_TEMPLATES_GRID_REQUEST',
	LAB_TEMPLATES_GRID_FAILURE				: 'LAB_TEMPLATES_GRID_FAILURE',
	LAB_TEMPLATES_GRID_SUCCESS				: 'LAB_TEMPLATES_GRID_SUCCESS',
	LAB_TEMPLATES_DELETE_REQUEST			: 'LAB_TEMPLATES_DELETE_REQUEST',
	LAB_TEMPLATES_DELETE_FAILURE			: 'LAB_TEMPLATES_DELETE_FAILURE',
	LAB_TEMPLATES_DELETE_SUCCESS			: 'LAB_TEMPLATES_DELETE_SUCCESS',
	LAB_TEMPLATES_RESET				    	: 'LAB_TEMPLATES_RESET',
	LAB_TEMPLATES_OPTION_REQUEST			: 'LAB_TEMPLATES_OPTION_REQUEST',
	LAB_TEMPLATES_OPTION_SUCCESS			: 'LAB_TEMPLATES_OPTION_SUCCESS',
	LAB_TEMPLATES_OPTION_FAILURE			: 'LAB_TEMPLATES_OPTION_FAILURE'
};
