/**
 * manageDrugsConstants
 *
 * @package                Safe Helth
 * @subpackage             manageDrugsConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for add drugs
 */
export const manageDrugsConstants = {
	SEETING_MANAGE_DRUG_ADD_REQUEST					: 'SEETING_MANAGE_DRUG_ADD_REQUEST',
	SEETING_MANAGE_DRUG_ADD_FAILURE					: 'SEETING_MANAGE_DRUG_ADD_FAILURE',
	SEETING_MANAGE_DRUG_ADD_SUCCESS					: 'SEETING_MANAGE_DRUG_ADD_SUCCESS',
	SEETING_MANAGE_DRUG_GRID_REQUEST				: 'SEETING_MANAGE_DRUG_GRID_REQUEST',
	SEETING_MANAGE_DRUG_GRID_FAILURE				: 'SEETING_MANAGE_DRUG_GRID_FAILURE',
	SEETING_MANAGE_DRUG_GRID_SUCCESS				: 'SEETING_MANAGE_DRUG_GRID_SUCCESS',
	SEETING_MANAGE_DRUG_DELETE_REQUEST				: 'SEETING_MANAGE_DRUG_DELETE_REQUEST',
	SEETING_MANAGE_DRUG_DELETE_FAILURE				: 'SEETING_MANAGE_DRUG_DELETE_FAILURE',
	SEETING_MANAGE_DRUG_DELETE_SUCCESS				: 'SEETING_MANAGE_DRUG_DELETE_SUCCESS',
	SEETING_MANAGE_DRUG_RESET				    	: 'SEETING_MANAGE_DRUG_RESET',
	SEETING_MANAGE_DRUG_OPTION_REQUEST				: 'SEETING_MANAGE_DRUG_OPTION_REQUEST',
	SEETING_MANAGE_DRUG_OPTION_SUCCESS				: 'SEETING_MANAGE_DRUG_OPTION_SUCCESS',
	SEETING_MANAGE_DRUG_OPTION_FAILURE				: 'SEETING_MANAGE_DRUG_OPTION_FAILURE'
};
