/**
 * patientReportsConstants
 *
 * @package                SafeHealth
 * @subpackage             patientReportsConstants
 * @category               Constants
 * @DateOfCreation         4 Oct 2018
 * @ShortDescription       This is responsible for Patient reports
 */
export const patientReportsConstants = {    
    LOGGED_IN				: 'LOGGED_IN',
    LOGGED_OUT				: 'LOGGED_OUT',

	PATIENT_REPORTS_GET_FILTER_DATA_REQUEST	: 'PATIENT_REPORTS_GET_FILTER_DATA_REQUEST',
	PATIENT_REPORTS_GET_FILTER_DATA_SUCCESS	: 'PATIENT_REPORTS_GET_FILTER_DATA_SUCCESS',
	PATIENT_REPORTS_GET_FILTER_DATA_FAILURE	: 'PATIENT_REPORTS_GET_FILTER_DATA_FAILURE',

	REPORTS_GET_FILTER_PATIENTS_DATA_REQUEST : 'REPORTS_GET_FILTER_PATIENTS_DATA_REQUEST',
	REPORTS_GET_FILTER_PATIENTS_DATA_SUCCESS : 'REPORTS_GET_FILTER_PATIENTS_DATA_SUCCESS',
	REPORTS_GET_FILTER_PATIENTS_DATA_FAILURE : 'REPORTS_GET_FILTER_PATIENTS_DATA_FAILURE',

	REPORTS_UNAUTHENTICATE	: 'REPORTS_UNAUTHENTICATE',
	PATIENT_REPORTS_RESET_STATE		: 'PATIENT_REPORTS_RESET_STATE',
};