/**
 * doctorDetailConstants
 *
 * @package                SafeHealth
 * @subpackage             doctorDetailConstants
 * @category               Constants
 * @DateOfCreation         22 june 2018
 * @ShortDescription       This is responsible for Doctor service action names
 */
export const doctorDetailConstants = {
  	DR_DETAIL_REQUEST: 'DR_DETAIL_REQUEST',
	DR_DETAIL_SUCCESS: 'DR_DETAIL_SUCCESS',
	DR_DETAIL_FAILURE: 'DR_DETAIL_FAILURE',
	DR_DETAIL_RESET_STATE: 'DR_DETAIL_RESET_STATE',
	BOOKING_REQUEST: 'BOOKING_REQUEST',
	BOOKING_SUCCESS: 'BOOKING_SUCCESS',
	BOOKING_FAILURE: 'BOOKING_FAILURE',
	LOGIN_SHOW: 'LOGIN_SHOW',
	SLOT_AVAILABLE_REQUEST: 'SLOT_AVAILABLE_REQUEST',
	SLOT_AVAILABLE_SUCCESS: 'SLOT_AVAILABLE_SUCCESS',
	SLOT_AVAILABLE_FAILURE: 'SLOT_AVAILABLE_FAILURE',
	RATING_ADD_REQUEST:'RATING_ADD_REQUEST',
	RATING_ADD_SUCCESS:'RATING_ADD_SUCCESS',
	RATING_ADD_FAILURE:'RATING_ADD_FAILURE',

};