/**
 * patientSymptomsConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             patientSymptomsConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const fxManagerConstants = {
	SYMPTOMS_OPTION_REQUEST				: 'SYMPTOMS_OPTION_REQUEST',
	SYMPTOMS_OPTION_FAILURE				: 'SYMPTOMS_OPTION_FAILURE',
	SYMPTOMS_OPTION_SUCCESS				: 'SYMPTOMS_OPTION_SUCCESS',
	SYMPTOMS_ADD_REQUEST				: 'SYMPTOMS_ADD_REQUEST',
	SYMPTOMS_ADD_FAILURE				: 'SYMPTOMS_ADD_FAILURE',
	SYMPTOMS_ADD_SUCCESS				: 'SYMPTOMS_ADD_SUCCESS',
	SYMPTOMS_GRID_REQUEST				: 'SYMPTOMS_GRID_REQUEST',
	SYMPTOMS_GRID_FAILURE				: 'SYMPTOMS_GRID_FAILURE',
	SYMPTOMS_GRID_SUCCESS				: 'SYMPTOMS_GRID_SUCCESS',
	SYMPTOMS_REST_ADD				: 'SYMPTOMS_REST_ADD',
	SYMPTOMS_UPDATE_REQUEST				: 'SYMPTOMS_UPDATE_REQUEST',
	SYMPTOMS_UPDATE_FAILURE				: 'SYMPTOMS_UPDATE_FAILURE',
	SYMPTOMS_UPDATE_SUCCESS				: 'SYMPTOMS_UPDATE_SUCCESS',
	SYMPTOMS_DELETE_REQUEST				: 'SYMPTOMS_DELETE_REQUEST',
	SYMPTOMS_DELETE_FAILURE				: 'SYMPTOMS_DELETE_FAILURE',
	SYMPTOMS_DELETE_SUCCESS				: 'SYMPTOMS_DELETE_SUCCESS',
};
