/**
 * patientVaccinationHistoryConstants
 *
 * @package                SAFE HEALTH
 * @subpackage             patientVaccinationHistoryConstants
 * @category               Constants
 * @DateOfCreation         21 Sept 2018
 * @ShortDescription       This is responsible for VACCINATION HISTORY action names
 */
export const patientVaccinationHistoryConstants = {
	PATIENT_VACCINATION_HISTORY_ADD_REQUEST					: 'PATIENT_VACCINATION_HISTORY_ADD_REQUEST',
	PATIENT_VACCINATION_HISTORY_ADD_FAILURE					: 'PATIENT_VACCINATION_HISTORY_ADD_FAILURE',
	PATIENT_VACCINATION_HISTORY_ADD_SUCCESS					: 'PATIENT_VACCINATION_HISTORY_ADD_SUCCESS',
	PATIENT_VACCINATION_HISTORY_GRID_REQUEST				: 'PATIENT_VACCINATION_HISTORY_GRID_REQUEST',
	PATIENT_VACCINATION_HISTORY_GRID_FAILURE				: 'PATIENT_VACCINATION_HISTORY_GRID_FAILURE',
	PATIENT_VACCINATION_HISTORY_GRID_SUCCESS				: 'PATIENT_VACCINATION_HISTORY_GRID_SUCCESS',
	PATIENT_VACCINATION_HISTORY_DELETE_REQUEST				: 'PATIENT_VACCINATION_HISTORY_DELETE_REQUEST',
	PATIENT_VACCINATION_HISTORY_DELETE_FAILURE				: 'PATIENT_VACCINATION_HISTORY_DELETE_FAILURE',
	PATIENT_VACCINATION_HISTORY_DELETE_SUCCESS				: 'PATIENT_VACCINATION_HISTORY_DELETE_SUCCESS',
	PATIENT_VACCINATION_HISTORY_RESET				    	: 'PATIENT_VACCINATION_HISTORY_RESET',
};
