export const clinicConstants = {
    DR_CLINIC_REQUEST        : 'DR_CLINIC_REQUEST',
    DR_CLINIC_SUCCESS        : 'DR_CLINIC_SUCCESS',
    DR_CLINIC_FAILURE        : 'DR_CLINIC_FAILURE',
    DR_CLINIC_SAVE_SUCCESS   : 'DR_CLINIC_SAVE_SUCCESS',
    DR_CLINIC_SAVE_FAILURE   : 'DR_CLINIC_SAVE_FAILURE',
    DR_CLINIC_REMOVE_SUCCESS : 'DR_CLINIC_REMOVE_SUCCESS',
    DR_CLINIC_REMOVE_FAILURE : 'DR_CLINIC_REMOVE_FAILURE',
    DR_CLINIC_RESET_STATE    : 'DR_CLINIC_RESET_STATE',
};


