export const doctorAwardsConstants = {
    DR_AWARDS_REQUEST        : 'DR_AWARDS_REQUEST',
    DR_AWARDS_SUCCESS        : 'DR_AWARDS_SUCCESS',
    DR_AWARDS_FAILURE        : 'DR_AWARDS_FAILURE',
    DR_AWARDS_EDIT_REQUEST   : 'DR_AWARDS_EDIT_REQUEST',
    DR_AWARDS_EDIT_SUCCESS   : 'DR_AWARDS_EDIT_SUCCESS',
    DR_AWARDS_EDIT_FAILURE   : 'DR_AWARDS_EDIT_FAILURE',
    DR_AWARDS_ADD_SUCCESS    : 'DR_AWARDS_ADD_SUCCESS',
    DR_AWARDS_ADD_FAILURE    : 'DR_AWARDS_ADD_FAILURE',
    DR_AWARDS_REMOVE_SUCCESS : 'DR_AWARDS_REMOVE_SUCCESS',
    DR_AWARDS_REMOVE_FAILURE : 'DR_AWARDS_REMOVE_FAILURE',
    DR_AWARDS_RESET_STATE    : 'DR_AWARDS_RESET_STATE',
};


