/**
 * doctorProfileConstants
 *
 * @package                SafeHealth
 * @subpackage             doctorProfileConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const doctorProfileConstants = {
    
    LOGGED_IN    				: 'LOGGED_IN',
    LOGGED_OUT      			: 'LOGGED_OUT',
	STATES_REQUEST				: 'STATES_REQUEST',
	STATES_SUCCESS				: 'STATES_SUCCESS',
	STATES_FAILURE				: 'STATES_FAILURE',
	CITIES_REQUEST				: 'CITIES_REQUEST',
	CITIES_SUCCESS				: 'CITIES_SUCCESS',
	CITIES_FAILURE				: 'CITIES_FAILURE',
	DR_PROFILE_DETAIL_REQUEST	: 'DR_PROFILE_DETAIL_REQUEST',
	DR_PROFILE_DETAIL_SUCCESS	: 'DR_PROFILE_DETAIL_SUCCESS',
	DR_PROFILE_DETAIL_FAILURE	: 'DR_PROFILE_DETAIL_FAILURE',
    DR_PROFILE_EDIT_REQUEST		: 'DR_PROFILE_EDIT_REQUEST',
	DR_PROFILE_EDIT_SUCCESS		: 'DR_PROFILE_EDIT_SUCCESS',
	DR_PROFILE_EDIT_FAILURE		: 'DR_PROFILE_EDIT_FAILURE',
	DR_PROFILE_UPDATE_SUCCESS 	: 'DR_PROFILE_UPDATE_SUCCESS',
	DR_PROFILE_UPDATE_FAILURE 	: 'DR_PROFILE_UPDATE_FAILURE',
	DR_PROFILE_RESET_STATE		: 'DR_PROFILE_RESET_STATE',
	DR_IMG_TYPE_VALID_MSG		: 'Only GIF, PNG, JPG, JPEG images are allows.',
	DR_IMG_SIZE_VALID_MSG		: 'Image size below 2MB.'
};

