/**
 * generalCheckupConstants Constants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             generalCheckupConstants
 * @category               Constants
 * @DateOfCreation         25 June 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const generalCheckupConstants = {
	GENERAL_CHECKUP_DATA_REQUEST		: 'GENERAL_CHECKUP_DATA_REQUEST',
	GENERAL_CHECKUP_DATA_FAILURE		: 'GENERAL_CHECKUP_DATA_FAILURE',
	GENERAL_CHECKUP_DATA_SUCCESS		: 'GENERAL_CHECKUP_DATA_SUCCESS',
	
	GENERAL_CHECKUP_ADD_UPDATE_REQUEST	: 'GENERAL_CHECKUP_ADD_UPDATE_UPDATE_REQUEST',
	GENERAL_CHECKUP_ADD_UPDATE_FAILURE	: 'GENERAL_CHECKUP_ADD_UPDATE_FAILURE',
	GENERAL_CHECKUP_ADD_UPDATE_SUCCESS	: 'GENERAL_CHECKUP_ADD_UPDATE_SUCCESS',

	GENERAL_CHECKUP_RESET_STATE			: 'GENERAL_CHECKUP_RESET_STATE'
};
