export const manageStaffConstants = {
    DR_STAFF_REQUEST        : 'DR_STAFF_REQUEST',
    DR_STAFF_SUCCESS        : 'DR_STAFF_SUCCESS',
    DR_STAFF_FAILURE        : 'DR_STAFF_FAILURE',
    DR_STAFF_SAVE_SUCCESS   : 'DR_STAFF_SAVE_SUCCESS',
    DR_STAFF_SAVE_FAILURE   : 'DR_STAFF_SAVE_FAILURE',
    DR_STAFF_REMOVE_SUCCESS : 'DR_STAFF_REMOVE_SUCCESS',
    DR_STAFF_REMOVE_FAILURE : 'DR_STAFF_REMOVE_FAILURE',
    DR_STAFF_RESET_STATE    : 'DR_STAFF_RESET_STATE',
};


