/**
 * patientProfileConstants
 *
 * @package                ILD India Registry
 * @subpackage             patientProfileConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientProfileConstants = {    
    LOGGED_IN						: 'LOGGED_IN',
    LOGGED_OUT						: 'LOGGED_OUT',
    PATIENT_PROFILE_EDIT_REQUEST	: 'PATIENT_PROFILE_EDIT_REQUEST',
	PATIENT_PROFILE_EDIT_SUCCESS	: 'PATIENT_PROFILE_EDIT_SUCCESS',
	PATIENT_PROFILE_EDIT_FAILURE	: 'PATIENT_PROFILE_EDIT_FAILURE',
	PATIENT_PROFILE_RESET_STATE		: 'PATIENT_PROFILE_RESET_STATE',
	PATIENT_PROFILE_UNAUTHENTICATE	: 'PATIENT_PROFILE_UNAUTHENTICATE',
	PATIENT_PROFILE_REQUEST			: 'PATIENT_PROFILE_REQUEST',
	PATIENT_PROFILE_FAILURE			: 'PATIENT_PROFILE_FAILURE',
	PATIENT_PROFILE_SUCCESS			: 'PATIENT_PROFILE_SUCCESS',

	PATIENT_UNAUTHENTICATE			: 'PATIENT_UNAUTHENTICATE',
	PATIENT_LIST_REQUEST			: 'PATIENT_LIST_REQUEST',
	PATIENT_LIST_FAILURE			: 'PATIENT_LIST_FAILURE',
	PATIENT_LIST_SUCCESS			: 'PATIENT_LIST_SUCCESS',

	PATIENT_PROFILE_UPDATE_SUCCESS  : 'PATIENT_PROFILE_UPDATE_SUCCESS' ,
	PATIENT_PROFILE_UPDATE_FAILURE  : 'PATIENT_PROFILE_UPDATE_FAILURE',

	PATIENT_VISIT_ID_REQUEST		: 'PATIENT_VISIT_ID_REQUEST',
	PATIENT_VISIT_ID_FAILURE		: 'PATIENT_VISIT_ID_FAILURE',
	PATIENT_VISIT_ID_SUCCESS		: 'PATIENT_VISIT_ID_SUCCESS',
	PATIENT_IMG_TYPE_VALID_MSG		: 'Only GIF, PNG, JPG, JPEG images are allows.',
	PATIENT_IMG_SIZE_VALID_MSG		: 'Image size below 2MB.'
};