/**
 * VISITDataConstants
 *
 * @package                Safehealth
 * @subpackage             visitDataConstants
 * @category               Constants
 * @DateOfCreation         07 August 2018
 * @ShortDescription       This is responsible for get static data action names
 */
export const visitDataConstants = {
	VISIT_COMPONENTS_DATA_REQUEST	: 'VISIT_COMPONENTS_DATA_REQUEST',
	VISIT_COMPONENTS_DATA_FAILURE	: 'VISIT_COMPONENTS_DATA_FAILURE',
	VISIT_COMPONENTS_DATA_SUCCESS	: 'VISIT_COMPONENTS_DATA_SUCCESS',
	VISIT_DATA_REQUEST				: 'VISIT_DATA_REQUEST',
	VISIT_DATA_FAILURE				: 'VISIT_DATA_FAILURE',
	VISIT_DATA_SUCCESS				: 'VISIT_DATA_SUCCESS',
	VISIT_UPDATE_DATA_REQUEST		: 'VISIT_UPDATE_DATA_REQUEST',
	VISIT_UPDATE_DATA_SUCCESS		: 'VISIT_UPDATE_DATA_SUCCESS',
	VISIT_UPDATE_DATA_FAILURE		: 'VISIT_UPDATE_DATA_FAILURE',
	VISIT_RESET_STATE				: 'VISIT_RESET_STATE',
	VISIT_COMPOMENTS_REQUEST		: 'VISIT_COMPOMENTS_REQUEST',
	VISIT_COMPOMENTS_FAILURE		: 'VISIT_COMPOMENTS_FAILURE',
	VISIT_COMPOMENTS_SUCCESS		: 'VISIT_COMPOMENTS_SUCCESS'
};
