/**
 * patientResidentPlaceConstants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             patientResidentPlaceConstants
 * @category               Constants
 * @DateOfCreation         16 May 2018
 * @ShortDescription       This is responsible for Doctor profile action names
 */
export const patientResidentPlaceConstants = {
	PATIENT_RESIDENT_PLACE_ADD_REQUEST		: 'PATIENT_RESIDENT_PLACE_ADD_REQUEST',
	PATIENT_RESIDENT_PLACE_ADD_FAILURE		: 'PATIENT_RESIDENT_PLACE_ADD_FAILURE',
	PATIENT_RESIDENT_PLACE_ADD_SUCCESS		: 'PATIENT_RESIDENT_PLACE_ADD_SUCCESS',
	PATIENT_RESIDENT_PLACE_GRID_REQUEST		: 'PATIENT_RESIDENT_PLACE_GRID_REQUEST',
	PATIENT_RESIDENT_PLACE_GRID_FAILURE		: 'PATIENT_RESIDENT_PLACE_GRID_FAILURE',
	PATIENT_RESIDENT_PLACE_GRID_SUCCESS		: 'PATIENT_RESIDENT_PLACE_GRID_SUCCESS',
	PATIENT_RESIDENT_PLACE_DELETE_REQUEST	: 'PATIENT_RESIDENT_PLACE_DELETE_REQUEST',
	PATIENT_RESIDENT_PLACE_DELETE_FAILURE	: 'PATIENT_RESIDENT_PLACE_DELETE_FAILURE',
	PATIENT_RESIDENT_PLACE_DELETE_SUCCESS	: 'PATIENT_RESIDENT_PLACE_DELETE_SUCCESS',
	PATIENT_RESIDENT_PLACE_RESET			: 'PATIENT_RESIDENT_PLACE_RESET',
};
