/**
 * medicineTemplatesConstants
 *
 * @package                Safe health
 * @subpackage             medicineTemplatesConstants
 * @category               Constants
 * @DateOfCreation         3 July 2018
 * @ShortDescription       This is responsible for get static data action names
 */
export const medicineTemplatesConstants = {
	SETTINGS_MED_LIST_DATA_REQUEST	: 'SETTINGS_MED_LIST_DATA_REQUEST',
	SETTINGS_MED_LIST_DATA_SUCCESS	: 'SETTINGS_MED_LIST_DATA_SUCCESS',
	SETTINGS_MED_LIST_DATA_FAILURE	: 'SETTINGS_MED_LIST_DATA_FAILURE',

	MEDICATION_EDIT_REQUEST		: 'MEDICATION_EDIT_REQUEST',
	MEDICATION_EDIT_SUCCESS		: 'MEDICATION_EDIT_SUCCESS',
	MEDICATION_EDIT_FAILURE		: 'MEDICATION_EDIT_FAILURE',

	SETTINGS_MED_TEMP_ADD_REQUEST		: 'SETTINGS_MED_TEMP_ADD_REQUEST',
	SETTINGS_MED_TEMP_ADD_SUCCESS		: 'SETTINGS_MED_TEMP_ADD_SUCCESS',
	SETTINGS_MED_TEMP_ADD_FAILURE		: 'SETTINGS_MED_TEMP_ADD_FAILURE',


	MEDICATION_TEMP_DELETE_REQUEST	: 'MEDICATION_TEMP_DELETE_REQUEST',
	MEDICATION_TEMP_DELETE_SUCCESS	: 'MEDICATION_TEMP_DELETE_SUCCESS',
	MEDICATION_TEMP_DELETE_FAILURE	: 'MEDICATION_TEMP_DELETE_FAILURE',

	DISCONTINUE_MEDICATION_REQUEST	: 'DISCONTINUE_MEDICATION_REQUEST',
	DISCONTINUE_MEDICATION_SUCCESS	: 'DISCONTINUE_MEDICATION_SUCCESS',
	DISCONTINUE_MEDICATION_FAILURE	: 'DISCONTINUE_MEDICATION_FAILURE',

	PATIENT_MEDICINE_DATA_REQUEST: 'PATIENT_MEDICINE_DATA_REQUEST',
	PATIENT_MEDICINE_DATA_SUCCESS: 'PATIENT_MEDICINE_DATA_SUCCESS',
	PATIENT_MEDICINE_DATA_FAILURE: 'PATIENT_MEDICINE_DATA_FAILURE',

	GET_MEDICINE_DATA_REQUEST	: 'GET_MEDICINE_DATA_REQUEST',
	GET_MEDICINE_DATA_SUCCESS	: 'GET_MEDICINE_DATA_SUCCESS',
	GET_MEDICINE_DATA_FAILURE	: 'GET_MEDICINE_DATA_FAILURE',
	
	MEDICATIONS_RESET_STATE		: 'MEDICATIONS_RESET_STATE',
	
	MEDICATION_TEMP_UPDATE_REQUEST:'MEDICATION_TEMP_UPDATE_REQUEST',
	MEDICATION_TEMP_UPDATE_SUCCESS:'MEDICATION_TEMP_UPDATE_SUCCESS',
	MEDICATION_TEMP_UPDATE_FAILURE:'MEDICATION_TEMP_UPDATE_FAILURE',

	SETTINGS_MED_TEMP_DATA_REQUEST:'SETTINGS_MED_TEMP_DATA_REQUEST',
	SETTINGS_MED_TEMP_DATA_SUCCESS:'SETTINGS_MED_TEMP_DATA_SUCCESS',
	SETTINGS_MED_TEMP_DATA_FAILURE:'SETTINGS_MED_TEMP_DATA_FAILURE',

	SETTINGS_MED_TEMP_FETCH_REQUEST:'SETTINGS_MED_TEMP_FETCH_REQUEST',
	SETTINGS_MED_TEMP_FETCH_SUCCESS:'SETTINGS_MED_TEMP_FETCH_SUCCESS',
	SETTINGS_MED_TEMP_FETCH_FAILURE:'SETTINGS_MED_TEMP_FETCH_FAILURE',
};
