/**
 * clinicalNotesConstants
 *
 * @package                Safe Health
 * @subpackage             clinicalNotesConstants
 * @category               Constants
 * @DateOfCreation         3 July 2018
 * @ShortDescription       This is responsible for get static data action names
 */
export const clinicalNotesConstants = {
	CLINICAL_NOTES_LIST_DATA_REQUEST	: 'CLINICAL_NOTES_LIST_DATA_REQUEST',
	CLINICAL_NOTES_LIST_DATA_SUCCESS	: 'CLINICAL_NOTES_LIST_DATA_SUCCESS',
	CLINICAL_NOTES_LIST_DATA_FAILURE	: 'CLINICAL_NOTES_LIST_DATA_FAILURE',

	CLINICAL_NOTES_EDIT_REQUEST			: 'CLINICAL_NOTES_EDIT_REQUEST',
	CLINICAL_NOTES_EDIT_SUCCESS			: 'CLINICAL_NOTES_EDIT_SUCCESS',
	CLINICAL_NOTES_EDIT_FAILURE			: 'CLINICAL_NOTES_EDIT_FAILURE',

	CLINICAL_NOTES_DELETE_REQUEST		: 'CLINICAL_NOTES_DELETE_REQUEST',
	CLINICAL_NOTES_DELETE_SUCCESS		: 'CLINICAL_NOTES_DELETE_SUCCESS',
	CLINICAL_NOTES_DELETE_FAILURE		: 'CLINICAL_NOTES_DELETE_FAILURE',

	PATIENT_CLINICAL_NOTES_DATA_REQUEST	: 'PATIENT_CLINICAL_NOTES_DATA_REQUEST',
	PATIENT_CLINICAL_NOTES_DATA_SUCCESS	: 'PATIENT_CLINICAL_NOTES_DATA_SUCCESS',
	PATIENT_CLINICAL_NOTES_DATA_FAILURE	: 'PATIENT_CLINICAL_NOTES_DATA_FAILURE',
	
	CLINICAL_NOTES_RESET_STATE			: 'CLINICAL_NOTES_RESET_STATE',
};
