/**
 * patientAllergiesConstants
 *
 * @package                Safe health
 * @subpackage             patientMedicalHistoryConstants
 * @category               Constants
 * @DateOfCreation         02 Aug 2018
 * @ShortDescription       This is responsible for Allergies action names
 */
export const patientAllergiesConstants = {
	PATIENT_ALLERGIES_ADD_REQUEST				: 'PATIENT_ALLERGIES_ADD_REQUEST',
	PATIENT_ALLERGIES_ADD_FAILURE				: 'PATIENT_ALLERGIES_ADD_FAILURE',
	PATIENT_ALLERGIES_ADD_SUCCESS				: 'PATIENT_ALLERGIES_ADD_SUCCESS',
	PATIENT_ALLERGIES_GRID_REQUEST				: 'PATIENT_ALLERGIES_GRID_REQUEST',
	PATIENT_ALLERGIES_GRID_FAILURE				: 'PATIENT_ALLERGIES_GRID_FAILURE',
	PATIENT_ALLERGIES_GRID_SUCCESS				: 'PATIENT_ALLERGIES_GRID_SUCCESS',
	PATIENT_ALLERGIES_DELETE_REQUEST			: 'PATIENT_ALLERGIES_DELETE_REQUEST',
	PATIENT_ALLERGIES_DELETE_FAILURE			: 'PATIENT_ALLERGIES_DELETE_FAILURE',
	PATIENT_ALLERGIES_DELETE_SUCCESS			: 'PATIENT_ALLERGIES_DELETE_SUCCESS',
	ALLERGIES_HISTORY_REQUEST 					: 'ALLERGIES_HISTORY_REQUEST',
	ALLERGIES_HISTORY_SUCCESS 					: 'ALLERGIES_HISTORY_SUCCESS',
	ALLERGIES_HISTORY_FAILURE 					: 'ALLERGIES_HISTORY_FAILURE',
	PATIENT_ALLERGIES_RESET				    	: 'PATIENT_ALLERGIES_RESET',
	ALLERGIES_HISTORY_ADD_UPDATE_REQUEST 		: 'ALLERGIES_HISTORY_ADD_UPDATE_REQUEST', 
	ALLERGIES_HISTORY_ADD_UPDATE_SUCCESS 		: 'ALLERGIES_HISTORY_ADD_UPDATE_SUCCESS', 
	ALLERGIES_HISTORY_ADD_UPDATE_FAILURE 		: 'ALLERGIES_HISTORY_ADD_UPDATE_FAILURE', 
};
