/**
 * appointmentsConstants
 *
 * @package                SafeHealth
 * @subpackage             appointmentsConstants
 * @category               Constants
 * @DateOfCreation         22 june 2018
 * @ShortDescription       This is responsible for Doctor service action names
 */
export const appointmentsConstants = {
  	APPOINTMENTS_REQUEST: 'APPOINTMENTS_REQUEST',
	APPOINTMENTS_SUCCESS: 'APPOINTMENTS_SUCCESS',
	APPOINTMENTS_FAILURE: 'APPOINTMENTS_FAILURE',
	APPOINTMENTS_RESET_STATE: 'APPOINTMENTS_RESET_STATE',
	TODAY_APPOINTMENT_REQUEST: 'TODAY_APPOINTMENT_REQUEST',
	TODAY_APPOINTMENT_SUCCESS: 'TODAY_APPOINTMENT_SUCCESS',
	TODAY_APPOINTMENT_FAILURE: 'TODAY_APPOINTMENT_FAILURE',
	GET_BOOKING_PATIENT_REQUEST : 'GET_BOOKING_PATIENT_REQUEST',
	GET_BOOKING_PATIENT_SUCCESS: 'GET_BOOKING_PATIENT_SUCCESS',
	GET_BOOKING_PATIENT_FAILURE: 'GET_BOOKING_PATIENT_FAILURE',
	GET_BOOKING_CLINIC_REQUEST:'GET_BOOKING_CLINIC_REQUEST',
	GET_BOOKING_CLINIC_SUCCESS:'GET_BOOKING_CLINIC_SUCCESS',
	GET_BOOKING_CLINIC_FAILURE:'GET_BOOKING_CLINIC_FAILURE',
	APPOINTMENT_TIME_REQUEST: 'APPOINTMENT_TIME_REQUEST',
	APPOINTMENT_TIME_SUCCESS: 'APPOINTMENT_TIME_SUCCESS',
	APPOINTMENT_TIME_FAILURE: 'APPOINTMENT_TIME_FAILURE',
	APPOINTMENT_ADD_REQUEST: 'APPOINTMENT_ADD_REQUEST',
	APPOINTMENT_ADD_SUCCESS: 'APPOINTMENT_ADD_SUCCESS',
	APPOINTMENT_ADD_FAILURE: 'APPOINTMENT_ADD_FAILURE',
	
};