/**
 * patientFamilyMedicalHistoryConstants Constants
 *
 * @package                ILD INDIA REGISTRY
 * @subpackage             generalCheckupConstants
 * @category               Constants
 * @DateOfCreation         25 June 2018
 * @ShortDescription       This is responsible for Patient Family Medical History action names
 */
export const patientFamilyMedicalHistoryConstants = {
    PATIENT_FAMILY_MEDICAL_HISTORY_DATA_REQUEST        	: 'PATIENT_FAMILY_MEDICAL_HISTORY_DATA_REQUEST',
    PATIENT_FAMILY_MEDICAL_HISTORY_DATA_FAILURE        	: 'PATIENT_FAMILY_MEDICAL_HISTORY_DATA_FAILURE',
    PATIENT_FAMILY_MEDICAL_HISTORY_DATA_SUCCESS        	: 'PATIENT_FAMILY_MEDICAL_HISTORY_DATA_SUCCESS',
    NEW_FAMILY_MEDICAL_HISTORY_DATA_REQUEST        		: 'NEW_FAMILY_MEDICAL_HISTORY_DATA_REQUEST',
    NEW_FAMILY_MEDICAL_HISTORY_DATA_FAILURE        		: 'NEW_FAMILY_MEDICAL_HISTORY_DATA_FAILURE',
    NEW_FAMILY_MEDICAL_HISTORY_DATA_SUCCESS        		: 'NEW_FAMILY_MEDICAL_HISTORY_DATA_SUCCESS',
    PATIENT_FAMILY_MEDICAL_HISTORY_RESET_STATE         	: 'PATIENT_FAMILY_MEDICAL_HISTORY_RESET_STATE'
};
